/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TODOInterface extends utils.Interface {
  functions: {
    "addTasks(string)": FunctionFragment;
    "listOfTasks(uint256)": FunctionFragment;
    "showTasks()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addTasks", values: [string]): string;
  encodeFunctionData(
    functionFragment: "listOfTasks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "showTasks", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addTasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listOfTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "showTasks", data: BytesLike): Result;

  events: {};
}

export interface TODO extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TODOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addTasks(
      task: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    listOfTasks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    showTasks(overrides?: CallOverrides): Promise<[string[]]>;
  };

  addTasks(
    task: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  listOfTasks(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  showTasks(overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    addTasks(task: string, overrides?: CallOverrides): Promise<void>;

    listOfTasks(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    showTasks(overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    addTasks(
      task: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    listOfTasks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    showTasks(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addTasks(
      task: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    listOfTasks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    showTasks(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
